### ISSUE TITLE
Continuous delivery for noop-discovery

### ISSUE THREAD

**Issue by arbitrarytech** [noop-cloud/noop-discovery#3]
We need a GitHub Action setup for automatically building and deploying updates of noop-discovery to NPM. Something must be worked out for bumping the `version` property in the `package.json` before pushing to NPM.

**Comment by derekwolpert** [comment]
Linking PR to this issue addresses this issue with a GitHub Action when running a `npm version` command in a local environment.

https://github.com/noop-cloud/noop-discovery/pull/6#issuecomment-680294260
