### ISSUE TITLE
Add component checksums

### ISSUE THREAD

**Issue by arbitrarytech** [noop-cloud/noop-discovery#4]
To detect changes between code versions of an individual component, the library should calculate a checksum of all files in the source which impact the component. This will allow us to avoid redundant builds. Optimally, the library would look at only the specific files included in the build context, for now, a checksum of the root directory may suffice.

**Comment by derekwolpert** [comment]
I believe https://github.com/noop-cloud/noop-discovery/pull/6 addresses parts of this issue, as it introduces more selective re-builds of components
